### ISSUE TITLE
Unable to build docker images [ERROR] asyncio.default_exception_handler(): Job processing failed

### ISSUE THREAD

**Issue by sethbeauchamp** [CiscoTestAutomation/xpresso#5]
When attempting to build a new image the process never completes properly. in the GUI it stays in the "build" status indefinitely. I tried using the YAML from the devnet sandbox to build an image as well as one of my own.

Since it mentioned a client connection problem, I tried setting the advertised URL to localhost as well as the IP of the machine. I am running this on the latest docker and macOS 10.15.6

```
workers_1               | 23/10/2020 16:10:41 [INFO] pyatsimagebuilder.builder.run(): Built image 'xpresso-test2:latest' successfully
workers_1               | 23/10/2020 16:10:41 [INFO] pyatsimagebuilder.builder.run(): Removing context directory
workers_1               | 23/10/2020 16:10:41 [INFO] apps.build_image.upload_log(): Uploading file logs...
workers_1               | 23/10/2020 16:10:41 [INFO] apps.build_image.upload_log_json(): Uploading back to genie service: http://localhost/api/v1/images/upload
workers_1               | 23/10/2020 16:10:41 [INFO] apps.build_image.upload_log_json(): Uploading-image: 5e219c99-45d4-4540-af88-228e5d18b85a
workers_1               | 23/10/2020 16:10:41 [INFO] apps.build_image.upload_log_json(): Upload-headers: {'Content-Type': 'application/json', 'Authorization': 'Jwt eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJvcmlnX2lhdCI6MTYwMzM4MjYxNCwidXNlcm5hbWUiOiJzYmVhdWNoYW1wIiwic2Vzc2lvbl9pZCI6InNlc3Npb25zOmNlZDMzOTBjLTk2NDAtNDM1Ny1hMzc5LTBmNDVlOWUxNjcwMiIsImV4cCI6NDc1Njk4MjYxNCwidG9rZW5fdHlwZSI6ImF1dG9tYXRpb24tdG9rZW4ifQ.vmNUjJb4Cy-v3N3zWqN51sCw5jsud2TbtIG5yH0cuWz089IbtpB7_XBuobnOet-r2CP2H1AySjkpC_pZDmYGqqTP3GXQ0yWfnE7sbh6ZxuTyjfgH1xQ89MPUZPrbCkytITMGvzna2VddVjLofPXCPXgl2Aizzq5KrW0XZTRrx0Nu154Nzjx29KRCtJNBC3MPWlYLe2Iw9D-lMnBe2OixSbvFP-HpfykBVZ8Ia8E28UGmtczwWZdB93h2fvGJaChLAaCBSSAG9AV80cYDQi4KTWlAfwC4A54OgLXi45K8m0vUp889ApBK4xs1YTeyzB1rcDzRGS5vUfKXS67V4MWoQA'}
workers_1               | 23/10/2020 16:10:41 [ERROR] apps.build_image.build_pyats_image(): Image building failed
workers_1               | Traceback (most recent call last):
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
workers_1               |     return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
workers_1               |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
workers_1               |     raise exceptions[0]
workers_1               |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
workers_1               |     sock = await self._connect_sock(
workers_1               |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
workers_1               |     await self.sock_connect(sock, address)
workers_1               |   File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
workers_1               |     return await fut
workers_1               |   File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 499, in _sock_connect
workers_1               |     sock.connect(address)
workers_1               | OSError: [Errno 99] Cannot assign requested address
workers_1               | 
workers_1               | The above exception was the direct cause of the following exception:
workers_1               | 
workers_1               | Traceback (most recent call last):
workers_1               |   File "/s3/src/apps/build_image.py", line 225, in build_pyats_image
workers_1               |     await upload_log(f_name, data)
workers_1               |   File "/s3/src/apps/build_image.py", line 96, in upload_log
workers_1               |     return await upload_log_json(ret, data)
workers_1               |   File "/s3/src/apps/build_image.py", line 64, in upload_log_json
workers_1               |     async with session.post(url,
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
workers_1               |     self._resp = await self._coro
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
workers_1               |     conn = await self._connector.connect(
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
workers_1               |     proto = await self._create_connection(req, traces, timeout)
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
workers_1               |     _, proto = await self._create_direct_connection(
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
workers_1               |     raise last_exc
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
workers_1               |     transp, proto = await self._wrap_create_connection(
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
workers_1               |     raise client_error(req.connection_key, exc) from exc
workers_1               | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:80 ssl:None [Cannot assign requested address]
workers_1               | 23/10/2020 16:10:41 [INFO] apps.build_image.upload_log(): Uploading file logs...
workers_1               | 23/10/2020 16:10:41 [INFO] apps.build_image.upload_log_json(): Uploading back to genie service: http://localhost/api/v1/images/upload
workers_1               | 23/10/2020 16:10:41 [INFO] apps.build_image.upload_log_json(): Uploading-image: 5e219c99-45d4-4540-af88-228e5d18b85a
workers_1               | 23/10/2020 16:10:41 [INFO] apps.build_image.upload_log_json(): Upload-headers: {'Content-Type': 'application/json', 'Authorization': 'Jwt eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJvcmlnX2lhdCI6MTYwMzM4MjYxNCwidXNlcm5hbWUiOiJzYmVhdWNoYW1wIiwic2Vzc2lvbl9pZCI6InNlc3Npb25zOmNlZDMzOTBjLTk2NDAtNDM1Ny1hMzc5LTBmNDVlOWUxNjcwMiIsImV4cCI6NDc1Njk4MjYxNCwidG9rZW5fdHlwZSI6ImF1dG9tYXRpb24tdG9rZW4ifQ.vmNUjJb4Cy-v3N3zWqN51sCw5jsud2TbtIG5yH0cuWz089IbtpB7_XBuobnOet-r2CP2H1AySjkpC_pZDmYGqqTP3GXQ0yWfnE7sbh6ZxuTyjfgH1xQ89MPUZPrbCkytITMGvzna2VddVjLofPXCPXgl2Aizzq5KrW0XZTRrx0Nu154Nzjx29KRCtJNBC3MPWlYLe2Iw9D-lMnBe2OixSbvFP-HpfykBVZ8Ia8E28UGmtczwWZdB93h2fvGJaChLAaCBSSAG9AV80cYDQi4KTWlAfwC4A54OgLXi45K8m0vUp889ApBK4xs1YTeyzB1rcDzRGS5vUfKXS67V4MWoQA'}
workers_1               | 23/10/2020 16:10:41 [ERROR] asyncio.default_exception_handler(): Job processing failed
workers_1               | job: <Job coro=<<coroutine object build_pyats_image at 0x7f8bc1bd0e40>>>
workers_1               | Traceback (most recent call last):
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
workers_1               |     return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
workers_1               |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
workers_1               |     raise exceptions[0]
workers_1               |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
workers_1               |     sock = await self._connect_sock(
workers_1               |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
workers_1               |     await self.sock_connect(sock, address)
workers_1               |   File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
workers_1               |     return await fut
workers_1               |   File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 499, in _sock_connect
workers_1               |     sock.connect(address)
workers_1               | OSError: [Errno 99] Cannot assign requested address
workers_1               | 
workers_1               | The above exception was the direct cause of the following exception:
workers_1               | 
workers_1               | Traceback (most recent call last):
workers_1               |   File "/s3/src/apps/build_image.py", line 240, in build_pyats_image
workers_1               |     await upload_log(f_name, data)
workers_1               |   File "/s3/src/apps/build_image.py", line 96, in upload_log
workers_1               |     return await upload_log_json(ret, data)
workers_1               |   File "/s3/src/apps/build_image.py", line 64, in upload_log_json
workers_1               |     async with session.post(url,
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
workers_1               |     self._resp = await self._coro
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
workers_1               |     conn = await self._connector.connect(
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
workers_1               |     proto = await self._create_connection(req, traces, timeout)
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
workers_1               |     _, proto = await self._create_direct_connection(
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
workers_1               |     raise last_exc
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
workers_1               |     transp, proto = await self._wrap_create_connection(
workers_1               |   File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
workers_1               |     raise client_error(req.connection_key, exc) from exc
workers_1               | aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:80 ssl:None [Cannot assign requested address]
```

YAML from sandbox

```
packages:  - 'pyats[full]'
  - tabulate
  - rest.connector
jobfiles:
  match:
    - .*_?job\.py
repositories:
  examples:
    url: 'https://github.com/CiscoTestAutomation/examples'
  soution_examples:
    url: 'https://github.com/CiscoTestAutomation/solutions_examples'
tag: 'pyats-sandbox-image:latest'
```

YAML of my own

```
packages:
  - 'pyats[full]'
jobfiles:
  match:
    - .*_?job\.py
repositories:
  examples:
    url: 'https://github.com/sethbeauchamp/xpresso-test'
tag: 'xpresso-test:latest'
```

**Comment by fdorani** [comment]
From the log, the Xpresso worker has already built the custom image and it just failed in the process of uploading the logs (upload_log_json function) back to an internal service (genie service). So either one of the Gateway or Genie services are down, or you've not set a proper **ADVERTISED_URL**. 

Could you make sure if you did follow all steps in deployment Readme part _2. Customization_ : https://github.com/CiscoTestAutomation/xpresso#deployment

Two solutions to resolve the issue: 
1) check the ADVERTISED_URL. if it's not properly set, update it's value from dashboard UI: <xpressourl>/system_management/microservices/common_settings > Gateway. Then stop/start Genie services 
docker-compose stop genie genie-celery genie-beat
docker-compose up -d genie genie-celery genie-beat
2) double check if all services are up and healthy especially: Gateway, Genie

Then try rebuilding a custom image.

**Comment by sethbeauchamp** [comment]
I had set the ADVERTISED_URL in the .env but after looking in the GUI as you mentioned, it still said localhost. It appears that this did not get set correctly via the .env file for some reason.

After setting it via GUI I can now build the image properly. Thanks.

**Comment by badalsoyantar** [comment]
closing as issue is resolved.
